import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import Works from '../components/works'

const Home: NextPage = () => {
  return (
    <div>  
       {/* className={styles.container}> */}
      <Head>
        <title>Edgelo - Site </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className='font-bold text-9xl'>Hello </div> */}
      <Masthead/>

      <AboutUs/>
      <Skills />
      <Works />
      
      {/* <Skills /> */}
      
      {/* <footer className={styles.footer}>
          <p className={styles.love}>          
                Made with ❤️ in LocalHost
                </p>

        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
           Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        
      </footer> */}
    </div>
  )
}

export default Home
